import type { Chat, MessageMap, User } from "./types";

export const ME = "me";

/** Cartoon avatars — real photos are never used as placeholders. */
const avatar = (seed: string, bg: string) =>
    `https://api.dicebear.com/9.x/avataaars/svg?seed=${encodeURIComponent(seed)}&backgroundColor=${bg}&radius=50`;

export const USERS: Record<string, User> = {
    me: {
        id: "me",
        name: "You",
        avatar: avatar("You-CCN", "c0aede"),
        about: "Learning never stops.",
        phone: "+91 90000 00000",
        email: "you@ccnmail.in",
        isOnline: true,
    },
    u1: {
        id: "u1",
        name: "Falguni Mam",
        avatar: avatar("Falguni", "ffd5dc"),
        about: "Available",
        designation: "Trainer · Network Security",
        phone: "+91 98765 43210",
        email: "falguni@ccnmail.in",
        isOnline: true,
    },
    u2: {
        id: "u2",
        name: "Kushal Sir",
        avatar: avatar("Kushal", "b6e3f4"),
        about: "Can't talk, CCN only",
        designation: "Trainer · Ethical Hacking",
        phone: "+91 98231 00012",
        email: "kushal@ccnmail.in",
        lastSeen: "today at 9:12 am",
    },
    u3: {
        id: "u3",
        name: "Nasreen Mam",
        avatar: avatar("Nasreen", "ffdfbf"),
        about: "The Best Tech, Best Future Empowering the Next Generation of IT",
        designation: "Academic Head",
        phone: "+91 97122 33445",
        email: "nasreen@ccnmail.in",
        isOnline: true,
    },
    u4: {
        id: "u4",
        name: "Fatema Mam",
        avatar: avatar("Fatema", "d1d4f9"),
        about: "Counselling · Admissions",
        designation: "Counsellor",
        phone: "+91 99001 12233",
        email: "fatema@ccnmail.in",
        isOnline: true,
    },
    u5: {
        id: "u5",
        name: "Ashish Sir",
        avatar: avatar("Ashish", "c0aede"),
        about: "Connecting Cyber Networks",
        designation: "Director",
        phone: "+91 90826 04209",
        email: "ashish@ccnmail.in",
        lastSeen: "today at 7:02 am",
    },
    u6: {
        id: "u6",
        name: "CA Amit Saini",
        avatar: avatar("Amit-Saini", "b6e3f4"),
        about: "Available",
        designation: "Accounts",
        phone: "+91 89478 91946",
        email: "accounts@ccnmail.in",
        lastSeen: "today at 10:15 am",
    },
    u7: {
        id: "u7",
        name: "Samreen Shaikh",
        avatar: avatar("Samreen", "ffd5dc"),
        about: "At the lab",
        designation: "Student · Ethical Hacking",
        phone: "+91 91375 94684",
        email: "samreen@ccnmail.in",
        lastSeen: "yesterday at 8:40 pm",
    },
    u8: {
        id: "u8",
        name: "Kartik CCN",
        avatar: avatar("Kartik", "ffdfbf"),
        about: "Available",
        designation: "Student · CCNA",
        phone: "+91 73049 18307",
        email: "kartik@ccnmail.in",
        isOnline: true,
    },
    u9: {
        id: "u9",
        name: "Sagar Sir",
        avatar: avatar("Sagar", "d1d4f9"),
        about: "Lab administrator",
        designation: "Lab Admin",
        phone: "+91 95334 45566",
        email: "sagar@ccnmail.in",
        lastSeen: "today at 8:55 am",
    },
    u10: {
        id: "u10",
        name: "Naveen Saini",
        avatar: avatar("Naveen", "b6e3f4"),
        about: "Busy",
        designation: "Student · CCNP",
        phone: "+91 98332 11445",
        email: "naveen@ccnmail.in",
        lastSeen: "today at 6:30 am",
    },
    u11: {
        id: "u11",
        name: "CCN Harshit",
        avatar: avatar("Harshit", "c0aede"),
        about: "Bug bounty hunter in progress",
        designation: "Student · Bug Bounty",
        phone: "+91 73049 18308",
        email: "harshit@ccnmail.in",
        isOnline: true,
    },
    u12: {
        id: "u12",
        name: "Shiv Acharekar",
        avatar: avatar("Shiv", "ffdfbf"),
        about: "Placements & drives",
        designation: "Placement Coordinator",
        phone: "+91 73049 18320",
        email: "placements@ccnmail.in",
        lastSeen: "today at 11:05 am",
    },
    u13: {
        id: "u13",
        name: "Siddhi",
        avatar: avatar("Siddhi", "ffd5dc"),
        about: "Available",
        designation: "Student · Cyber Forensics",
        phone: "+91 90820 16762",
        email: "siddhi@ccnmail.in",
        lastSeen: "today at 9:48 am",
    },
    u14: {
        id: "u14",
        name: "Dev",
        avatar: avatar("Dev", "d1d4f9"),
        about: "Available",
        designation: "Student · CCNA",
        phone: "+91 90040 22118",
        email: "dev@ccnmail.in",
        lastSeen: "yesterday at 10:20 pm",
    },
    u15: {
        id: "u15",
        name: "Connecting Cyber Networks-HR",
        avatar: avatar("CCN-HR", "b6e3f4"),
        about: "Hiring & internships",
        designation: "HR",
        phone: "+91 77380 57188",
        email: "hr@ccnmail.in",
        isOnline: true,
    },
    u16: {
        id: "u16",
        name: "Cyber Security Instructor",
        avatar: avatar("Instructor", "c0aede"),
        about: "Available",
        designation: "Trainer · SOC",
        phone: "+91 98332 73347",
        email: "instructor@ccnmail.in",
        lastSeen: "today at 8:05 am",
    },
};

const J = (userId: string, role: "owner" | "admin" | "member", joinedOn = "12 Jan 2026") => ({
    userId,
    role,
    joinedOn,
});

export const CHATS: Chat[] = [
    {
        id: "c1",
        type: "community",
        name: "CCN Community",
        description:
            "Official community of Connecting Cyber Networks. Announcements, placement drives, workshop invites and security advisories are posted here. Only admins can send messages.",
        createdBy: "u5",
        createdOn: "02 Jan 2026",
        announcementOnly: true,
        linkedGroupIds: ["c2", "c3"],
        unreadCount: 3,
        muted: false,
        pinned: true,
        favorite: true,
        members: [
            J("u5", "owner", "02 Jan 2026"),
            J("u4", "admin", "02 Jan 2026"),
            J("u9", "admin", "05 Jan 2026"),
            J("me", "member", "24 Jul 2026"),
            J("u1", "member"), J("u2", "member"), J("u3", "member"), J("u6", "member"),
            J("u7", "member"), J("u8", "member"), J("u10", "member"), J("u11", "member"),
            J("u12", "member"), J("u13", "member"), J("u14", "member"), J("u15", "member"),
        ],
    },
    {
        id: "c2",
        type: "group",
        name: "CCNA Batch 2025-2026",
        description:
            "Batch group for CCNA 2025-2026. Session links, lab files and assignment deadlines are shared here. Keep discussions on topic.",
        createdBy: "u1",
        createdOn: "18 Feb 2026",
        unreadCount: 2,
        muted: false,
        pinned: true,
        members: [
            J("u1", "owner", "18 Feb 2026"),
            J("u9", "admin", "18 Feb 2026"),
            J("me", "member", "20 Feb 2026"),
            J("u8", "member"), J("u7", "member"), J("u10", "member"),
            J("u11", "member"), J("u13", "member"), J("u14", "member"),
        ],
    },
    {
        id: "c3",
        type: "group",
        name: "Account Department",
        description: "Fee receipts, invoices and payment confirmations. Working hours 10:00 am – 6:30 pm.",
        createdBy: "u6",
        createdOn: "04 Mar 2026",
        unreadCount: 0,
        muted: true,
        pinned: false,
        members: [J("u6", "owner", "04 Mar 2026"), J("u4", "admin"), J("me", "member"), J("u3", "member")],
    },
    {
        id: "c4",
        type: "personal",
        name: "Falguni Mam",
        avatar: USERS.u1.avatar,
        createdBy: "u1",
        createdOn: "24 Jul 2026",
        unreadCount: 0,
        muted: false,
        pinned: false,
        favorite: true,
        members: [J("u1", "member"), J("me", "member")],
    },
    {
        id: "c5",
        type: "personal",
        name: "Kartik CCN",
        avatar: USERS.u8.avatar,
        createdBy: "u8",
        createdOn: "24 Jul 2026",
        unreadCount: 1,
        muted: false,
        pinned: false,
        typingUserId: "u8",
        members: [J("u8", "member"), J("me", "member")],
    },
    {
        id: "c6",
        type: "personal",
        name: "Fatema Mam",
        avatar: USERS.u4.avatar,
        createdBy: "u4",
        createdOn: "24 Jul 2026",
        unreadCount: 0,
        muted: false,
        pinned: false,
        members: [J("u4", "member"), J("me", "member")],
    },
    {
        id: "c7",
        type: "personal",
        name: "Samreen Shaikh",
        avatar: USERS.u7.avatar,
        createdBy: "u7",
        createdOn: "24 Jul 2026",
        unreadCount: 0,
        muted: false,
        pinned: false,
        members: [J("u7", "member"), J("me", "member")],
    },
    {
        id: "c8",
        type: "personal",
        name: "Naveen Saini",
        avatar: USERS.u10.avatar,
        createdBy: "u10",
        createdOn: "24 Jul 2026",
        unreadCount: 0,
        muted: false,
        pinned: false,
        members: [J("u10", "member"), J("me", "member")],
    },
    {
        id: "c9",
        type: "personal",
        name: "CA Amit Saini",
        avatar: USERS.u6.avatar,
        createdBy: "u6",
        createdOn: "24 Jul 2026",
        unreadCount: 0,
        muted: false,
        pinned: false,
        members: [J("u6", "member"), J("me", "member")],
    },
    {
        id: "c10",
        type: "personal",
        name: "Siddhi",
        avatar: USERS.u13.avatar,
        createdBy: "u13",
        createdOn: "24 Jul 2026",
        unreadCount: 0,
        muted: false,
        pinned: false,
        members: [J("u13", "member"), J("me", "member")],
    },
];

const readers = (ids: string[], at: string) => ids.map((userId) => ({ userId, at }));

export const MESSAGES: MessageMap = {
    c1: [
        {
            id: "c1m1", chatId: "c1", senderId: "u5", dayKey: "Yesterday", time: "09:40 am",
            status: "read", system: true,
            html: "<p>You were added to <strong>CCN Community</strong> by Ashish Sir</p>",
        },
        {
            id: "c1m2", chatId: "c1", senderId: "u5", dayKey: "Yesterday", time: "09:41 am", status: "read",
            html: "<p><strong>Welcome to the CCN Community.</strong></p><p>Use this space to stay updated on:</p><ul><li>Placement drives &amp; interview calls</li><li>Free workshops and CTF events</li><li>Security advisories from the lab team</li></ul>",
            pinned: true,
            reactions: [{ emoji: "👍", userIds: ["u1", "u8", "me"] }, { emoji: "🔥", userIds: ["u11"] }],
            readBy: readers(["u1", "u8", "u3"], "Yesterday 09:45 am"),
        },
        {
            id: "c1m3", chatId: "c1", senderId: "u1", dayKey: "Today", time: "09:05 am", status: "read",
            html: "<p>New batch for <em>Advanced Penetration Testing</em> opens on 5th Oct. Seats are limited — brochure attached.</p>",
            attachments: [
                { id: "a1", kind: "file", name: "CCN-Adv-PenTest-Brochure.pdf", url: "#", size: "2.4 MB", ext: "PDF" },
            ],
            reactions: [{ emoji: "🎉", userIds: ["u7", "u13"] }],
        },
        {
            id: "c1m4", chatId: "c1", senderId: "u9", dayKey: "Today", time: "09:22 am", status: "delivered",
            html: "<p>Lab servers will be down for maintenance tonight between <strong>11:00 pm</strong> and <strong>1:00 am</strong>. Please save your work.</p>",
            attachments: [
                { id: "a2", kind: "image", name: "lab-maintenance.png", url: "https://picsum.photos/seed/lab1/640/420" },
            ],
        },
    ],
    c2: [
        {
            id: "c2m1", chatId: "c2", senderId: "u1", dayKey: "Yesterday", time: "09:40 am",
            status: "read", system: true,
            html: "<p>Falguni Mam created group <strong>CCNA Batch 2025-2026</strong></p>",
        },
        {
            id: "c2m2", chatId: "c2", senderId: "u1", dayKey: "Yesterday", time: "09:50 am", status: "read",
            html: "<p>Today's session on <strong>Subnetting &amp; VLSM</strong> starts at 11:00 AM sharp. Join link below.</p><p><a href=\"https://meet.ccn.in/ccna-live\" target=\"_blank\" rel=\"noopener noreferrer nofollow\">https://meet.ccn.in/ccna-live</a></p>",
            pinned: true,
            reactions: [{ emoji: "👍", userIds: ["me", "u8", "u7", "u10"] }],
            readBy: readers(["u8", "u7"], "Yesterday 09:52 am"),
        },
        {
            id: "c2m3", chatId: "c2", senderId: "me", dayKey: "Yesterday", time: "09:52 am", status: "read",
            html: "<p>Joining on time, ma'am.</p>",
            readBy: readers(["u1", "u8", "u7", "u10"], "Yesterday 09:55 am"),
            deliveredTo: readers(["u13"], "Yesterday 09:53 am"),
        },
        {
            id: "c2m4", chatId: "c2", senderId: "u9", dayKey: "Today", time: "10:12 am", status: "read",
            html: "<p>Lab topology file for today's practical.</p>",
            attachments: [
                { id: "a3", kind: "file", name: "ccna-lab-topology.pkt", url: "#", size: "820 KB", ext: "PKT" },
            ],
        },
        {
            id: "c2m5", chatId: "c2", senderId: "u8", dayKey: "Today", time: "10:20 am", status: "read",
            html: "<p>Sir, my packet tracer is throwing a licence error. Screenshot attached.</p>",
            attachments: [
                { id: "a4", kind: "image", name: "error.png", url: "https://picsum.photos/seed/err1/500/360" },
                { id: "a5", kind: "image", name: "error2.png", url: "https://picsum.photos/seed/err2/500/360" },
            ],
            replyTo: { messageId: "c2m4", senderId: "u9", preview: "Lab topology file for today's practical." },
        },
        {
            id: "c2m6", chatId: "c2", senderId: "me", dayKey: "Today", time: "10:24 am", status: "delivered",
            html: "<p>Reinstall from the lab portal — the bundled licence expired last week.</p>",
            deliveredTo: readers(["u1", "u8", "u7"], "Today 10:24 am"),
            readBy: readers(["u8"], "Today 10:25 am"),
            starred: true,
        },
    ],
    c3: [
        {
            id: "c3m1", chatId: "c3", senderId: "u6", dayKey: "Yesterday", time: "09:40 am",
            status: "read", system: true,
            html: "<p>You were added to <strong>Account Department</strong></p>",
        },
        {
            id: "c3m2", chatId: "c3", senderId: "u6", dayKey: "Yesterday", time: "09:55 am", status: "read",
            html: "<p>Please submit your fee receipts before <strong>30th July</strong>. Late submissions attract a ₹500 penalty.</p>",
            pinned: true,
        },
        {
            id: "c3m3", chatId: "c3", senderId: "me", dayKey: "Yesterday", time: "10:05 am", status: "read",
            html: "<p>Receipt attached, kindly confirm.</p>",
            attachments: [{ id: "a6", kind: "file", name: "fee-receipt-july.pdf", url: "#", size: "410 KB", ext: "PDF" }],
            readBy: readers(["u6", "u4"], "Yesterday 10:08 am"),
        },
        {
            id: "c3m4", chatId: "c3", senderId: "u6", dayKey: "Yesterday", time: "10:09 am", status: "read",
            html: "<p>Received and verified. Thank you.</p>",
            reactions: [{ emoji: "✅", userIds: ["me"] }],
        },
    ],
    c4: [
        {
            id: "c4m1", chatId: "c4", senderId: "u1", dayKey: "Yesterday", time: "03:55 pm", status: "read",
            html: "<p>Connecting Cyber Networks offers <strong>Ethical Hacking, CCNP Security, CCIE Security, Checkpoint CCSA/CCSE, PALO ALTO PCNSA, Bug Bounty, Penetration Testing</strong> and <strong>Cyber Forensics</strong>.</p><blockquote><p>A career in cyber security offers high salary growth, fast advancement and continuous learning.</p></blockquote>",
        },
        {
            id: "c4m2", chatId: "c4", senderId: "me", dayKey: "Yesterday", time: "04:00 pm", status: "read",
            html: "<p>Thank you ma'am. Which track would you suggest after CCNA?</p>",
            readBy: readers(["u1"], "Yesterday 04:01 pm"),
        },
        {
            id: "c4m3", chatId: "c4", senderId: "u1", dayKey: "Yesterday", time: "04:04 pm", status: "read",
            html: "<p>Go for <em>CCNP Security</em>, then Checkpoint. Full roadmap here:</p><p><a href=\"https://www.connectingcybernetworks.com/\" target=\"_blank\" rel=\"noopener noreferrer nofollow\">https://www.connectingcybernetworks.com/</a></p>",
            reactions: [{ emoji: "❤️", userIds: ["me"] }],
        },
        {
            id: "c4m4", chatId: "c4", senderId: "u1", dayKey: "Today", time: "11:15 am", status: "read",
            html: "",
            attachments: [{ id: "a7", kind: "audio", name: "voice-note.ogg", url: "#", duration: 34 }],
        },
        {
            id: "c4m5", chatId: "c4", senderId: "me", dayKey: "Today", time: "11:20 am", status: "read",
            html: "<p>Understood, I'll prepare the notes tonight.</p>",
            replyTo: { messageId: "c4m4", senderId: "u1", preview: "Voice message", kind: "audio" },
            readBy: readers(["u1"], "Today 11:21 am"),
        },
        {
            id: "c4m6", chatId: "c4", senderId: "u1", dayKey: "Today", time: "11:34 am", status: "read",
            html: "<p>Here are the lab shots from yesterday's session.</p>",
            attachments: [
                { id: "a8", kind: "image", name: "lab-a.jpg", url: "https://picsum.photos/seed/ccn1/600/420" },
                { id: "a9", kind: "image", name: "lab-b.jpg", url: "https://picsum.photos/seed/ccn2/600/420" },
                { id: "a10", kind: "image", name: "lab-c.jpg", url: "https://picsum.photos/seed/ccn3/600/420" },
                { id: "a11", kind: "image", name: "lab-d.jpg", url: "https://picsum.photos/seed/ccn4/600/420" },
            ],
            reactions: [{ emoji: "👏", userIds: ["me"] }],
        },
    ],
    c5: [
        {
            id: "c5m1", chatId: "c5", senderId: "u8", dayKey: "Today", time: "09:40 am", status: "delivered",
            html: "<p>Bro, did you complete the subnetting worksheet?</p>",
        },
    ],
    c6: [
        {
            id: "c6m1", chatId: "c6", senderId: "u4", dayKey: "Today", time: "08:10 am", status: "read",
            html: "<p>Your counselling session is confirmed for Friday 4 pm.</p>",
        },
        {
            id: "c6m2", chatId: "c6", senderId: "me", dayKey: "Today", time: "08:12 am", status: "read",
            html: "<p>Noted, thank you.</p>",
            readBy: readers(["u4"], "Today 08:13 am"),
        },
    ],
    c7: [],
    c8: [],
    c9: [],
    c10: [],
};

/** Media shown in the info panel gallery, per chat. */
export const CHAT_MEDIA: Record<string, string[]> = {
    c1: ["https://picsum.photos/seed/lab1/200/200"],
    c2: ["https://picsum.photos/seed/err1/200/200", "https://picsum.photos/seed/err2/200/200"],
    c4: [
        "https://picsum.photos/seed/ccn1/200/200",
        "https://picsum.photos/seed/ccn2/200/200",
        "https://picsum.photos/seed/ccn3/200/200",
        "https://picsum.photos/seed/ccn4/200/200",
        "https://picsum.photos/seed/ccn5/200/200",
        "https://picsum.photos/seed/ccn6/200/200",
    ],
};
